name: Feature Request
description: Suggest a new feature for the TeleTask integration
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!
        Please describe what you'd like to see added to the integration.

  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: A clear and concise description of the feature you'd like.
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Why would this feature be useful? What problem does it solve?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you considered any alternative solutions or workarounds?

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or examples about the feature request.
